#docker-compose file
version: '3'

services:
  nest-auth:
    container_name: nest-auth
    image: nest-auth:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
