#docker-compose file
version: '3'

services:
  nest-auth:
    container_name: nest-auth
    image: nest-auth:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    env_file:
      - .env
